### ISSUE TITLE
HmIP-STV wrong Mode

### ISSUE THREAD

**Issue by HB-Therm** [SukramJ/hahomematic#1236]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The HmIP-STV device is shown in HA as a vibration sensor. In RaspberryMatic, however, a position sensor is stored!
![Bildschirmfoto 2023-10-05 um 11 55 34](https://github.com/danielperna84/hahomematic/assets/144919799/00841569-c42b-4b64-86d3-6477797fa09c)
![Bildschirmfoto 2023-10-05 um 12 01 21](https://github.com/danielperna84/hahomematic/assets/144919799/724ee9c3-5001-4be2-abed-8eec87fa6bb1)

### What version of HomematicIP (local) has the issue?

1.44.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20230826

### What hardware are you running for your system?

ESXi

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
The default setting for the `motion` parameter of the HmIP-STV is the device_class `motion`.
Since we don't do any customization for sensors, the simplest solution would be for you to do the customizing in HA yourself, for example. adjusts the device_class.
Possible device_classes can be found [here](https://developers.home-assistant.io/docs/core/entity/binary-sensor#available-device-classes), but there is no device_class for position. Maybe `moving` as an option.
Of course you can also make the setting via the UI. Click on the entity -> click on the gear -> Select entry under show as.
