### ISSUE TITLE
Raspberry Pi 5 Integration schlägt fehl

### ISSUE THREAD

**Issue by Seoman2023** [SukramJ/hahomematic#1335]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [ ] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HomematicIP (local) lässt sich nicht integrieren (Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"} )

Benutzt wird die neueste Dev Version

Core: 2024.1.0.dev20231218
Supervisor: 2023.12.0
Operating System: 11.3.dev20231221
Frontend: 20231218.0.dev

### What version of HomematicIP (local) has the issue?

1.51.0

### What was the last working version of HomematicIP (local)?

1.51.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Pi5

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Looks like a problem on your system with the development version of HA.
There is no problem on my dev system.

Basically i don't support dev versions of HA

**Comment by epruesse** [comment]
@Seoman2023 Go into HACS, enable the beta versions, install the latest beta. There was a change in HA that needed adjustment on the custom_homematic side (entity description needs to derive from abc or you get a metaclass type error). 

@SukramJ You could mark this as fixed. It's not technically hahomematic but custom_homematic, but then issues are disabled over there. The metaclass thing displays as "configuration flow could not be loaded" (or Geman  equivalent) because the first thing you do to load the integration is the configuration workflow, which on import raises the type error.
