### ISSUE TITLE
HM-Sec-Key doesnt work probably since HA 2024.4

### ISSUE THREAD

**Issue by pietro4711** [SukramJ/hahomematic#1486]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since HA 2024.4 the HM-Sec-Key only locks/opens after "double" closing/opening.
Problem description:
HM-Sec-Key is locked (homematic view) -> press unlock in HA -> state in HA "changed to none".
 -> press unlock once again (in HA) -> "changed to unlocked"

and vice versa.

### What version of HomematicIP (local) has the issue?

1.590b0 and 1.58

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.6.20240316

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Please enable debug logging for the integration and lock, unlock afterwards

**Comment by pietro4711** [comment]
here we go
[home-assistant_homematicip_local_2024-04-09T05-42-30.648Z.log](https://github.com/danielperna84/hahomematic/files/14915520/home-assistant_homematicip_local_2024-04-09T05-42-30.648Z.log)

**Comment by SukramJ** [comment]
Based on the log you added i can say that the integration works as expected:

Your request to unlock (i guess) is send correctly to the CCU:
`__ASYNC_REQUEST: ('setValue', ('EEQ0034772:1', 'STATE', True))`

The CCU answers with : 
Still locked / not unlocked
`EVENT: interface_id = Homematic-BidCos-RF, channel_address = EEQ0034772:1, parameter = STATE, value = False`
But Moving
`EVENT: interface_id = Homematic-BidCos-RF, channel_address = EEQ0034772:1, parameter = DIRECTION, value = 1`

The missing event from the CCU **before** your next click to unlock is:
`EVENT: interface_id = Homematic-BidCos-RF, channel_address = EEQ0034772:1, parameter = STATE, value = True`

Unless the event from CCU is received, the integration cannot switch the state to unlock.
I think the problem is not related to HA.
Best thing to verify this is to downgrade HA and the integration to a previous version.

**Comment by pietro4711** [comment]
The interesting thing is, when I lock/unlock the HM-Sec-Key within the CCU-Webfrontend everything works as expected....
Here is a screenshot of HA where you can see, the strange effect: 
![image](https://github.com/danielperna84/hahomematic/assets/44528095/a3cb14a7-ee71-48ae-be17-dae51b3e8a98)

07:41:42 press unlock within HA
07:41:42 changed to closing ?
07:41:50 Türschloss was locked ?
07:41:50 Richtung changed to none 

now I press unlock once again:
07:41:54 Türschloss was unlocked


Ok, I will downgrade and test it again...

Thanks for you help!

**Comment by pietro4711** [comment]
You were absolutely right - apparently a bug in the current Rasperrymatic - after rebooting the CCU, everything is running correctly again.
Thank you very much!
