### ISSUE TITLE
HmIP-eTRV-C-2 valve drive opening degree „0“ not displayed correctly

### ISSUE THREAD

**Issue by marc965** [SukramJ/hahomematic#166]
**custom_component/hahomematic version (if applicable):**
0.19.1

**Home Assistant version (if applicable):**
2021.12.9

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): CCU3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20211218

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? HmIP-RF, BidCos-RF

**Describe the bug**
opening degree of valve drive HmIP-eTRV-C-2 is displaying normally 
between 1 - 0,1 but opening degree „0“ (valve completely closed) is displayed as
„not available“, „nicht mehr verfügbar“. 

**Expected behavior**
opening degree „0“ (completely closed) ist displayed normally and not as „nicht mehr verfügbar“.

**Screenshots**

![](https://user-images.githubusercontent.com/22775515/149126924-bc88b138-b1fe-47cc-b7c9-e77b7d74b1f5.png)

**Comment by Lemocin** [comment]
It seems to happen [here](https://github.com/danielperna84/hahomematic/blob/4efd7c137ce88807ea058e559e26a278490ecab2/hahomematic/platforms/number.py#L50), and the thermostat level is not the only thing which is affected. It's just the only one one we see. 

Python treats 0 and 0.0 as False, so we have to check if the value is not undefined instead of the current version.
I created a PR with the fix.
