### ISSUE TITLE
enable GLOBAL_BUTTON_LOCK  on HmIP-eTRV-2 ?

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#911]
### Discussed in https://github.com/danielperna84/hahomematic/discussions/910

<div type='discussions-op-text'>

<sup>Originally posted by **jarcikw** February  2, 2023</sup>
Is it possible to use this in this integration in Home Assistant when calling service ? 
I cannot use channel 0 where it should be , channels starts with 1 
It is working when i enable this in CCU3

service: homematicip_local.put_paramset
data:
  paramset_key: MASTER
  paramset:
    GLOBAL_BUTTON_LOCK: true
  device_address: 000a18a996f62d
  channel: 0

</div>

**Comment by SukramJ** [comment]
@jarcikw: Fix will be part of 1.28.1

**Comment by jarcikw** [comment]
@SukramJ 

Tested In developer tools tab

**I can enable/disable GLOBAL_BUTTON_LOCK when i choose device from dropdown list.**
_service: homematicip_local.put_paramset 
data: <br>
  channel: 0
  paramset_key: MASTER
  paramset:
    GLOBAL_BUTTON_LOCK: false
  device_id: 7a89542ab53b1c8ad952e9e637d8cb1a_

**It doesn't work when i enter "Device address"** 
_service: homematicip_local.put_paramset
data:
  channel: 0
  paramset_key: MASTER
  paramset:
    GLOBAL_BUTTON_LOCK: false
  device_address: 000a18a996f62d_


**Is it expected behaviour ?**

**Comment by SukramJ** [comment]
Please don't comment on closed issue!

> Is it expected behaviour ?

What do you think?

Hint: device_address are always upper case.
